Asm
Sher13/first-term pull request #2
Opened 2020-06-29 19:01 UTC by Sher13

2020-06-29 20:56 UTC, kt-cpp requested changes

2020-06-29 20:56 UTC, kt-cpp commented on asm/mul.asm
> +		mov		rcx, 256
Длина аперандов уже лежит в rcx, не надо её хардкодить, иначе функция сломается

2020-06-29 20:56 UTC, kt-cpp commented on asm/mul.asm
> +		mov		rcx, 129
Снова хардкод

2020-06-29 20:56 UTC, kt-cpp commented on asm/mul.asm
> +; copy r12 to r11 (long long)
[minor] Не хватает в контракте откуда берётся длина

2020-06-29 20:56 UTC, kt-cpp commented on asm/mul.asm
> +		call		copy
Ты кладёшь в `r12` `rsi`, который указывает на число размера 128, но копируешь при это 129. Кажется это бага

2020-06-30 08:36 UTC, Sher13 commented on asm/mul.asm
> +		mov		rcx, 256
Кажется, я только занулил 256 qword в r13?
Это ошибка?
И rcx я при этом сохранил...

2020-06-30 08:56 UTC, Sher13 commented on asm/mul.asm
> +		mov		rcx, 256
эмм, надо было сделать `mul rcx,  2`??

2020-06-30 11:55 UTC, kt-cpp requested changes
Ещё чуть чуть

2020-06-30 11:55 UTC, kt-cpp commented on asm/mul.asm
> +		call		copy
Сейчас лучше, но теперь другой потенциальный баг. У тебя по адресу `r11` лежит буфер размера 256. Так вот:
* Кажется его можно сделать 129, т.е. `rcx + 1`
* Ты копируешь туда только первые 128 _цифр_, но используется 129 включая ведущий 0, который вообще-то нужно после каждый операций обновлять ибо ты его потенциально портишь. Поправь, если я не прав

2020-06-30 12:21 UTC, kt-cpp approved these changes

2020-06-30 12:21 UTC, merged