add vector
Sher13/first-term pull request #3
Opened 2020-07-01 15:40 UTC by Sher13

2020-07-01 16:16 UTC, kt-cpp requested changes
В целом что-то с форматированием:
* Функции слипаются
* Случайные пробелы перед треугольными скобками
* Пробелы вокруг бинарных операторов
* Списки инициализации едут
* Пробелы  после таких ключевых слова как `while` или `for`
Настрой форматирование. Ребята с курса тебе помогут с этим

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
>      typedef T const* const_iterator;
[note] `using` более современный и читабельный вариант

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +    };                                   // O(1) nothrow
[minor] Лучше использовать инициализацию поле класса в конструкторе по возможности. Тут точно такая возможность есть

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +#endif // VECTOR_H
[minor] Гитхаб подсказывает, что забыли перенос сроки в конце файла

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        vector <T> nw(other);
[note] Указывать `<T>` тут не обязательно, т.к. по дефолту наследуется от объемлющего типа

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        T x = val;
Этой копии можно избежать при отсутствии переаллокаций в векторе

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        if (size_ == capacity_)
[minor] Нет смысла экономить на фигурных скобках, так только ухудшается читаемость кода кем-то дргуим

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +            change_capacity(2 * (size_ + 1));
Тут намеренно выделяются НЕ степени двойки? Если нет, то это лучше сделать через тернаный оператор, чтобы были степени двойки

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +            change_capacity(new_cap);
[minor] Снова экономия фигурных скобок

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        std::swap(capacity_, other.capacity_);
[note] Лучше сделать `using std::swap`, а потом обращаться к нему без префикса неймспейса. Это привнесёт сюда потенциально свапы, которые не лежат в `std`

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        new(data_+size_) T(val);
`push_back`?)

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        size_t ind = pos - data_;
1. `size_t` не подходит для разницы указателей, для этого есть `ptrdiff_t`
2. [note] Более консистентно будет вычитать из итератора итератор, хоть и итератор тут просто алиас на указатель

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        data_[ind] = val;
Из-за присваиваний у тебя происходит двойное копирование `val`, а ещё проседают гарантии. Подумай как без присваиваний сделать

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        size_t n = last - first;
Снова тип для разницы указателей

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +            data_[i] = data_[i+n];
Снова присваивания там, где можно обойтись более лёгким и надёжным инструментом. Представь что у тебя `vector<vector<int>>`, сколько тут будет ненужным коприрований..

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        return insert(pos-data_+data_, val);
[note] Тут и во многих подобных местах снова актуальны слова про вычитание указателей и итераторов. А ещё хорошо бы расставить скобки, чтобы показать, что ты хочешь этим сказать

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +            return;
Лучше бы эта проверка была снаружи, немного странно иметь её в семантике

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        capacity_ = new_cap;
[note] Семантически лучше выглядит, если бы использовала для очистки отдельную функцию, которую перевызываешь в `clear`, чтобы не возить туда сюда здесь размер вектора

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +    void copy(T* from, T* to, size_t n) {
Довольно странная семантика у функции, которая может удалить указатель, что ей передали. Если тебе хочется автоконтроль за нововыделенными данными, то может инкапсиулировать его в эту функцию и пусть она возвращает указатель на новые хорошие данные?

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +#include <iostream>
[minor] Зачем он тут?

2020-07-01 16:16 UTC, kt-cpp commented on vector/vector.h
> +        capacity_ = new_cap;
Я вижу больше одного места, где подобная функцию может использоваться в коде

2020-07-01 16:40 UTC, Sher13 commented on vector/vector.h
> +            return;
Но тогда ее придется написать в нескольких местах,  так она только здесь.

2020-07-01 20:37 UTC, Sher13 commented on vector/vector.h
> +            return;
тогда ее придется писать в нескольких местах, а так она только тут.
я думал, это оптимизация...

2020-07-01 20:38 UTC, Sher13 commented on vector/vector.h
> +#include <iostream>
Ну кажется он оптимальней, чем две библиотеки для `size_t` и `swap` ?

2020-07-01 20:46 UTC, Sher13 commented on vector/vector.h
> +        T x = val;
вот тут вообще не понял(
кажется проверять на отсутствие переаллокаций я не могу....

2020-07-01 21:17 UTC, Sher13 commented on vector/vector.h
> +    void copy(T* from, T* to, size_t n) {
а это про `copy` или `change_capacity` ?

2020-07-02 13:29 UTC, kt-cpp commented on vector/vector.h
> +#include <iostream>
иногда лучше подключить 2, чем 1. это связано с размером библиотек. но в этом случае я не уверен

2020-07-02 13:32 UTC, kt-cpp commented on vector/vector.h
> +        T x = val;
кажется вопрос исчерпан

2020-07-02 13:44 UTC, kt-cpp approved these changes
все эти комментарии note и не обязательны

2020-07-02 13:44 UTC, kt-cpp commented on vector/vector.h
> +            : data_(nullptr), size_(0), capacity_(0) {
: vector()

2020-07-02 13:44 UTC, kt-cpp commented on vector/vector.h
> +        if (other.size_ == 0)
лучше if (other.size()) { и дальше те 3 строки }

2020-07-02 13:44 UTC, kt-cpp commented on vector/vector.h
> +            return;
else {}

2020-07-02 13:44 UTC, kt-cpp commented on vector/vector.h
> +    iterator erase(iterator pos) {
для erase и insert достаточно перегрузок для const_iterator

2020-07-02 13:44 UTC, kt-cpp commented on vector/vector.h
> +        T* to;
обычно такие штуки выносят в статик метод типа alloc_

2020-07-02 13:44 UTC, kt-cpp commented on vector/vector.h
> +            while(size) {
немного копипасты с delete_

2020-07-02 13:45 UTC, merged