add bigint
Sher13/first-term pull request #4
Opened 2020-07-04 13:03 UTC by Sher13

2020-07-05 18:24 UTC, lejabque commented on bigint/big_integer.cpp
> +        }
мб убрать циклы и заменить на какой-нибудь insert?

2020-07-05 18:24 UTC, lejabque commented on bigint/big_integer.cpp
> +        s.erase(s.begin());
Удалять из начала может быть дорого тоже

2020-07-05 18:25 UTC, Sher13 commented on bigint/big_integer.cpp
> +        s.erase(s.begin());
предлагаешь реверснуть и удалять?
хмм, блин, так и было, да((

2020-07-07 18:48 UTC, kt-cpp requested changes
Много мелочей

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +}
Стоит сделать более говорящее название, get_чего_именно?

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
>      b.sign = false;
abs()

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        return 0 - ans;
это же просто -ans

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    // '<' = 1;  '>' = -1; '==' 0;
Кажется, это делается в три строки ровно так, как описанно в комментарии (с тернарником в одну)

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        return false;
Даже вокруг однострочных блоков кода в ифах и циклах должны стоять фигурные скобки

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        sign = false;
Существуют числа с нулевым количеством цифр?

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +void big_integer::bitToTwo() {
это неДжава, а си_плюс_плюс (нужно, чтобы везде был одинаковый кодстайл)

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if ((digits.back() & 2147483648) != 2147483648)
Выглядит как константа, которую нужно вынести

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer b(bb);
[не критично] Не то чтобы самый лучший нейминг

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer rez;
[совсем не критично] rez от слова rezul'tat или всё-таки result?

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
>  }
= default на самом деле

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    digits.push_back(b);
Как насчёт обойтись без лишних переменных при помощи static_cast'a? К тому же битность лонг не специфицирована и вы играете с переполнениями, используйте int64 в таких случаях

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            st10 *= 10;
Можно вынести в константы

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    long long borrow = 0;
Опять int64, исправьте везде

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            long long x = (long long) digits[i] + (long long) b + carry;
Не используйте С style касты

2020-07-07 18:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (a.digits.empty()) {
Реализуйте нормальное хранение нуля (без пустых чисел), заведите константу ZERO = big_integer(0) и сравнивайте с ней в таких ситуациях

2020-07-07 18:53 UTC, Sher13 commented on bigint/big_integer.cpp
> +    // '<' = 1;  '>' = -1; '==' 0;
ну там обратная зависимость)

2020-07-07 18:54 UTC, Sher13 commented on bigint/big_integer.cpp
> +        sign = false;
Да, ноль.

2020-07-07 18:57 UTC, Sher13 commented on bigint/big_integer.cpp
> +}
fixed

2020-07-07 18:57 UTC, Sher13 commented on bigint/big_integer.cpp
>      b.sign = false;
fixed

2020-07-07 18:57 UTC, Sher13 commented on bigint/big_integer.cpp
> +        return 0 - ans;
fixed

2020-07-07 18:57 UTC, Sher13 commented on bigint/big_integer.cpp
> +        return false;
fixed

2020-07-07 18:58 UTC, Sher13 commented on bigint/big_integer.cpp
> +void big_integer::bitToTwo() {
fixed

2020-07-07 19:01 UTC, Sher13 commented on bigint/big_integer.cpp
> +    big_integer rez;
rezul'tat, да, англ не мое))))

2020-07-07 19:02 UTC, Sher13 commented on bigint/big_integer.cpp
>  }
fixed

2020-07-07 19:04 UTC, Sher13 commented on bigint/big_integer.cpp
> +    digits.push_back(b);
fixed

2020-07-07 19:08 UTC, Sher13 commented on bigint/big_integer.cpp
> +            st10 *= 10;
fixed

2020-07-07 19:08 UTC, Sher13 commented on bigint/big_integer.cpp
> +    long long borrow = 0;
fixed

2020-07-07 19:08 UTC, Sher13 commented on bigint/big_integer.cpp
> +            long long x = (long long) digits[i] + (long long) b + carry;
fixed

2020-07-07 19:12 UTC, Sher13 commented on bigint/big_integer.cpp
> +    if (a.digits.empty()) {
Ну ладно сравнивать, но почему ноль нельзя так хранить?

2020-07-07 19:17 UTC, Sher13 commented on bigint/big_integer.cpp
> +    if ((digits.back() & 2147483648) != 2147483648)
fixed

2020-07-07 19:21 UTC, Sher13 commented on bigint/big_integer.cpp
> +    if (a.digits.empty()) {
У нас по умолчанию `big_integer() == 0`кажется объективным при стандартном конструкторе ничего не класть в `digits`

2020-07-07 19:43 UTC, Sher13 commented on bigint/big_integer.cpp
> +    if (a.digits.empty()) {
fixed

2020-07-07 19:44 UTC, Sher13 commented on bigint/big_integer.cpp
> +        sign = false;
Уже нет)
fixed

2020-07-07 20:31 UTC, kt-cpp requested changes

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        return false;
Нет не fixed, пройдитесь по коду

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    // '<' = 1;  '>' = -1; '==' 0;
Тогда перенесите поближе к тому месту, где функция используется

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if ((digits.back() & radix/2) != radix/2)
пробелы: radix / 2
везде должно быть так

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
>  }
По-хорошему other должен быть уже отнормирован, так что просто = default

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        sign = true;
Тернарник

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        }
Как насчёт в случае неравенства знаков просто отправлять в вычитание

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        return *this;
Копипасточка
Плюс не особо понятно зачем отдельно разбирать этот случай

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        const uint32_t new_radix = 10;
Константы заглавными буквами

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +static const uint64_t radix = 4294967296;
и тут

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    rhs %= 32;
Любые такие захардкоденные значения должны быть вынесены в константы

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        uint32_t rem = b.div_little(1000000000);
Константы

2020-07-07 20:31 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    b.sign = false;
big_integer b(abs(a)), мы ж не просто так abs написали

2020-07-07 21:07 UTC, Sher13 commented on bigint/big_integer.cpp
> +    b.sign = false;
fixed

2020-07-07 21:07 UTC, Sher13 commented on bigint/big_integer.cpp
> +        uint32_t rem = b.div_little(1000000000);
fixed

2020-07-07 21:07 UTC, Sher13 commented on bigint/big_integer.cpp
> +    rhs %= 32;
fixed

2020-07-07 21:07 UTC, Sher13 commented on bigint/big_integer.cpp
> +static const uint64_t radix = 4294967296;
fixed

2020-07-07 21:07 UTC, Sher13 commented on bigint/big_integer.cpp
> +        const uint32_t new_radix = 10;
fixed

2020-07-07 21:07 UTC, Sher13 commented on bigint/big_integer.cpp
> +        return *this;
fixed

2020-07-07 21:10 UTC, Sher13 commented on bigint/big_integer.cpp
> +        return *this;
Ну при конструкторе от строки и в делении мы довольно часто умножаем на короткое число, так что в этом случае не хочется создавать отдельный бигинт. Но тут оно правда бесполезно, да.

2020-07-07 21:11 UTC, Sher13 commented on bigint/big_integer.cpp
> +        sign = true;
Лучше))
`sign = (a < 0);`
ну, я верю, что лучше)

2020-07-07 21:11 UTC, Sher13 commented on bigint/big_integer.cpp
>  }
fixed

2020-07-07 21:19 UTC, Sher13 commented on bigint/big_integer.cpp
> +    if ((digits.back() & radix/2) != radix/2)
fixed

2020-07-07 21:34 UTC, Sher13 commented on bigint/big_integer.cpp
> +        }
Ok....

2020-07-08 17:11 UTC, merged