add opt
Sher13/first-term pull request #5
Opened 2020-07-08 17:15 UTC by Sher13

2020-07-08 18:59 UTC, kt-cpp requested changes

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/cow_vector.h
> +};
[minor] перенос в конце файла

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/cow_vector.h
> +        data_ = std::vector<uint32_t>(n);
[minor] Инициализация членов

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/cow_vector.h
> +        data_ = std::vector<uint32_t>(b);
[minor] Инициализация членов

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/cow_vector.h
> +    }
[minor] Можно было и без геттера

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +size_t const SIZE = 6;
[minor] constexpr и запрятать внутрь класса

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +            }
[minor] `std::copy`

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +        }
Дорого не сама динамическая память, а её выделение. Нет смысла сжиматься, если уже выделил память

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +    }
[minor] Можно делать меньше переаллокаций, если не пушбекать а честно выделить достаточно памяти. Для большой версии вектор сам имеет нужную перегрузку инсерта

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +                small[i] = small[i + n];
[minor] Экономим на скобках

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +    }
[minor] Можно реализовать эффективнее если разобрать случаи

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +            }
[minor] А тут почему не вызвать `std::reverse`?

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +        std::swap(small, b.small);
[note] Надеюсь ты понимаешь, что это работает только потому что у тебя всё дофига trivially и ты меняешь местами большую из альтернатив

2020-07-08 18:59 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +        }
[minor] У вектора есть конструктор от двух итератов. Лучше его переиспользовать, чтобы ихбежать тут лишние копирования и создание локальной копии буффера

2020-07-08 19:05 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +        std::swap(small, b.small);
ну да))
хотя я думала, это потому что указатель по размеру меньше, чем массив.

2020-07-08 19:10 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +size_t const SIZE = 6;
fixed

2020-07-08 19:10 UTC, Sher13 commented on bigint-optimized/cow_vector.h
> +        data_ = std::vector<uint32_t>(n);
fixed

2020-07-08 19:10 UTC, Sher13 commented on bigint-optimized/cow_vector.h
> +        data_ = std::vector<uint32_t>(b);
fixed

2020-07-08 19:12 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +            }
fixed

2020-07-08 19:13 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +        }
fixed

2020-07-08 19:41 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +    }
fixed

2020-07-08 19:42 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +                small[i] = small[i + n];
fixed

2020-07-08 19:43 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +            }
fixed

2020-07-08 19:46 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +        }
fixed

2020-07-08 19:47 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +    }
fixed)

2020-07-08 19:48 UTC, Sher13 commented on bigint-optimized/cow_vector.h
> +};
fixed

2020-07-08 19:49 UTC, Sher13 commented on bigint-optimized/cow_vector.h
> +    }
Я не придумал, как доставать объект из другого(
только если нам гарантируется, что вектор лежит вначале структуры.... каст?
но как-то некрасиво(

2020-07-08 22:20 UTC, kt-cpp commented on bigint-optimized/cow_vector.h
> +    }
Всё ещё можно

2020-07-08 22:27 UTC, kt-cpp requested changes

2020-07-08 22:27 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +            }
[minor] `std::fill`

2020-07-08 22:27 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +            }
[minor] `std::fill`

2020-07-08 22:27 UTC, kt-cpp commented on bigint-optimized/so_vector.h
> +            }
[minor] `std::rotate`

2020-07-09 14:40 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +            }
fixed

2020-07-09 14:40 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +            }
fixed

2020-07-09 14:40 UTC, Sher13 commented on bigint-optimized/so_vector.h
> +            }
fixed

2020-07-09 14:40 UTC, Sher13 commented on bigint-optimized/cow_vector.h
> +    }
fixed

2020-07-09 16:30 UTC, kt-cpp approved these changes

2020-07-09 16:30 UTC, merged